aws_common_inventory: PROD
aws_common_region: "ap-southeast-2"
aws_vpc_cidr: '10.1.0.0/16'
aws_vpc_name: "{{ aws_common_inventory | upper }}"
tags:
  Name: "{{ aws_vpc_name }}"
  Ansible: "Ansible"
  ENV: "{{ aws_common_inventory }}"
  REGION: "{{ aws_common_region }}"


aws_subnets:

# PROD vpc 10.1.0.0/16
### public, 0,100,200

  - name: PROD-public-a
    cidr: 10.1.0.0/24
    az: ap-southeast-2a
    tag_az: A
    subnet_type: public

  - name: PROD-public-b
    cidr: 10.1.100.0/24
    az: ap-southeast-2b
    tag_az: B
    subnet_type: public

  - name: PROD-public-c
    cidr: 10.1.200.0/24
    az: ap-southeast-2c
    tag_az: C
    subnet_type: public

###private, 1,101,201
  - name: PROD-private-a
    cidr: 10.1.1.0/24
    az: ap-southeast-2a
    tag_az: A
    subnet_type: private

  - name: PROD-private-b
    cidr: 10.1.101.0/24
    az: ap-southeast-2b
    tag_az: B
    subnet_type: private

  - name: PROD-private-c
    cidr: 10.1.201.0/24
    az: ap-southeast-2c
    tag_az: C
    subnet_type: private

### security groups
aws_security_groups:
  - name: PROD-juice-bar
    tag:
      ENV: PROD
      product: juice-bar
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
